//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Indra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResponse
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int Response { get; set; }
        public System.DateTime DateResponse { get; set; }
    
        public virtual User User { get; set; }
    }
}
